apiVersion: v1
kind: Service
metadata:
  name: customerapi-svc
  namespace: proxy
  labels:
    app: otokoccustomerapi
    service: customerapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: customerapi