apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
  namespace: proxy
  labels:
    app: customerapi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: customerapi
  template:
    metadata:
      labels:
        app: customerapi
        service: customerapi
    spec:
      containers:
        - name: customerapi
          image: cahityusuf/customerapi:v2 #$(Build.BuildId)
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.3"
            limits:
              memory: "500Mi"
              cpu: "0.3"