apiVersion: v1
kind: Service
metadata:
  name: productapi-svc
  namespace: proxy
  labels:
    app: otokocproductapi
    service: productapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: productapi