apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  labels:
    app: otokocreverseproxy
    service: reverseproxy
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: reverseproxy